### ISSUE TITLE
add support for AVLdiy.cn device

### ISSUE THREAD

**Issue by mikk150** [OpenLightingProject/ola#1073]
It is basically the same as Anymau
All I did was change 
```c
const char AnymauDMXFactory::EXPECTED_MANUFACTURER[] = "AVLdiy.cn";
const char AnymauDMXFactory::EXPECTED_PRODUCT[] = "D512";
const uint16_t AnymauDMXFactory::PRODUCT_ID = 0x8888;
const uint16_t AnymauDMXFactory::VENDOR_ID = 0x03EB;
```
and udev rules
```
SUBSYSTEM=="usb*", ACTION=="add", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="8888", MODE="0666", GROUP="plugdev"
SUBSYSTEM=="usb*", ACTION=="add", SYSFS{idVendor}=="03eb", SYSFS{idProduct}=="8888", MODE="0666", GROUP="plugdev"
```
and worked

**Comment by peternewman** [comment]
Hi @mikk150 , do you want to open a pull request with the relevant changes then please? There are some instructions here https://github.com/OpenLightingProject/ola/blob/master/plugins/usbdmx/README.md , but basically just copy and rename the four Anyma files (and their classes) and add a few lines to SyncronizedWidgetObserver.h . Then add rather than replace the udev rules.
