### ISSUE TITLE
cppunit 1.14.0 and ac_cv_gnu_plus_plus_98=no

### ISSUE THREAD

**Issue by ilovezfs** [OpenLightingProject/ola#1244]
I've just upgraded `cppunit` to version 1.14.0 in Homebrew, and it seems that this breaks the `ola` build. I've worked around the issue with the following diff:

```
diff --git a/Formula/ola.rb b/Formula/ola.rb
index d288ec8..78947cd 100644
--- a/Formula/ola.rb
+++ b/Formula/ola.rb
@@ -3,7 +3,7 @@ class Ola < Formula
   homepage "https://www.openlighting.org/ola/"
   url "https://github.com/OpenLightingProject/ola/archive/0.10.3.tar.gz"
   sha256 "474db6752940cea6cd9493dcbeeb13429b5d29f4777973d08738cb5ef04c9dcd"
-  revision 1
+  revision 2
   head "https://github.com/OpenLightingProject/ola.git"
 
   bottle do
@@ -36,7 +36,12 @@ class Ola < Formula
     sha256 "846eb4846f19598affdc349d817a8c4c0c68fd940303e6934725c889f16f00bd"
   end
 
+  needs :cxx11
+
   def install
+    ENV.cxx11
+    ENV["ac_cv_gnu_plus_plus_98"] = "no"
+
     resource("protobuf-c").stage do
       system "./configure", "--disable-dependency-tracking",
                             "--prefix=#{buildpath}/vendor/protobuf-c"
```

Not sure if this is going to impact your CI or not.

Also, it would be good not to need to manually specify ac_cv_gnu_plus_plus_98=no since `ENV.cxx11` should be sufficient, but configure currently overrides that unless 98 is forced to no.

(See https://github.com/Homebrew/homebrew-core/pull/13103)

**Comment by peternewman** [comment]
Thanks for the heads up, yes it has broken our CI.

For info our reasoning for not having moved on before is here:
https://github.com/OpenLightingProject/ola/blob/master/README.developer#L83

Unfortunately some of the newer compilers were failing if left in auto (e.g. https://github.com/OpenLightingProject/ola/issues/1028) hence why we had to pin the build own to C++98.

I may try and roll the Mac builds back to cppunit 1.13.0 for the moment, until we decide how to proceed with that.

**Comment by ilovezfs** [comment]
@peternewman you might want to cherry-pick https://github.com/Homebrew/brew/pull/2406 and give that a try.

**Comment by ilovezfs** [comment]
@peternewman https://github.com/Homebrew/brew/pull/2406 has been merged, so no need to cherry-pick it if you want to try using the bottle URL for 1.13.0

**Comment by peternewman** [comment]
Thanks @ilovezfs . Is there an official way to find the bottle name, I just looked at a previous successful run.

Also how do I update homebrew to support that feature, I'm guessing it needs a release, as it currently just fails:
https://travis-ci.org/peternewman/ola/jobs/228538602#L384

**Comment by ilovezfs** [comment]
@peternewman actually it looks like that will raise a mismatched version error unfortunately. Instead, you can do this:
```
bash-3.2$ cd $(brew --repo homebrew/core)
bash-3.2$ pwd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
bash-3.2$ git log --oneline -- Formula/cppunit.rb|head -5
6484b32911 cppunit: update 1.14.0 bottle.
e6e43cf6a3 cppunit 1.14.0
b9984305de cppunit: add test, HTTPS URL
8c4f669fae cppunit: drop universal
fec46784a4 cppunit: update 1.13.2 bottle.
bash-3.2$ git checkout e6e43cf6a3^ -- Formula/cppunit.rb
bash-3.2$ brew install cppunit
==> Downloading https://homebrew.bintray.com/bottles/cppunit-1.13.2.el_capitan.bottle.1.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/cppunit-1.13.2.el_capitan.bottle.1.tar.gz
==> Pouring cppunit-1.13.2.el_capitan.bottle.1.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/cppunit/1.13.2: 94 files, 1.2MB
bash-3.2$
```

**Comment by peternewman** [comment]
The second option has done the trick thanks @ilovezfs . Useful to know for the future too if/when you upgrade other packages which break us.

**Comment by ilovezfs** [comment]
@peternewman cool I left a comment: https://github.com/OpenLightingProject/ola/pull/1247/files#r115123065

**Comment by yoe** [comment]
This was also filed in Debian as [862128](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862128)

**Comment by peternewman** [comment]
Thanks @yoe . I thought we might avoid this on Debian although I guess you're testing during deb building.

I think the cppunit-config thing in the RedHat report at https://bugzilla.redhat.com/show_bug.cgi?id=1311694 is a different issue that's already been fixed in OLA.

I wonder if a better compromise for now is to detect cppunit >= 1.14.0 during configure and disable the tests if they've not been explicitly asked for, or ask the user to disable them or something. At least then the build can continue until we rewrite everything to support C++11 (or switch to an alternative testing framework).

Do you have any gut feeling on how the gnuradio thing with C++11 may go @yoe ?

**Comment by yoe** [comment]
@peternewman, while I could disable the test suite when building the Debian package, it's something that's frowned upon in Debian. It would not signal us when things break like e.g. the SPARC build did recently. I would prefer to avoid that option if we can.

Isn't it possible to drop the hard requirement for C++98 in some way instead? AFAIK that's done because otherwise we get deprecation warnings for things that are done in a different way in C++14, but it *is* possible to deal with that in a different way instead, which would solve this problem...

Alternatively, the maintainer of cppunit would have to be be convinced to maintain two versions of cppunit for the benefit of code like ola that is sticking to C++98, but I don't think that is going to fly with him. To be fair, I also don't think it is a viable long term strategy.

**Comment by peternewman** [comment]
For info, I've opened a PR with the tactical fix for now of just looking for cppunit < 1.14.0 ( #1250 ) so we can get 0.10.4 out of the door, then look at fixing this properly. I came to similar reasoning regards the deprecation stuff @yoe , I suspect the ideal will be to detect cppunit >= 1.14.0 and then add some more ignore deprecation options and allow/force C++11 . Then all the other builds should still act as canaries for other newly deprecated features.

**Comment by peternewman** [comment]
The Red Hat issue was reported as https://github.com/OpenLightingProject/ola/issues/1043 and fixed in #1044 so has been sorted for some time.

**Comment by peternewman** [comment]
@ilovezfs and @yoe I think I may now have fixed this for machines with cppunit 1.14.0 and above too. The patch in https://github.com/OpenLightingProject/ola/pull/1258 has now gone in if you fancy giving it a spin (you'll have to compile from git for now). Travis doesn't seem to require any on OS X, but I wonder if it may need some more deprecation warnings silenced on Linux.

**Comment by peternewman** [comment]
Bump, @ilovezfs and @yoe are you happy with this, if so I'll release 0.10.5 soon.

**Comment by yoe** [comment]
compiling from master WFM after installing cppunit 1.14 on a Debian box.

**Comment by peternewman** [comment]
@ilovezfs ? I'll get 0.10.5 out soon if you're happy this has solved your issue too?

**Comment by ilovezfs** [comment]
@peternewman yes, it works! I'm still seeing https://github.com/OpenLightingProject/ola/issues/1165 but that's unrelated, of course.

**Comment by peternewman** [comment]
Excellent, thanks both, I'll close this now, 0.10.5 will hopefully appear fairly soon.
