### ISSUE TITLE
Running olad at boot using systemd

### ISSUE THREAD

**Issue by alphancioglu** [OpenLightingProject/ola#1441]
I am trying to run olad at system start on arch linux. I am using systemd because it is the recommended way by the arch wiki. Below is the service unit file(olad.service) I created.

```
[Unit]
Description=OLA Daemon

[Service]
ExecStart=/usr/local/bin/olad --daemon --syslog
User=alp

[Install]
WantedBy=multi-user.target
```

"User=alp" field means that the process is started as my user instead of the default root because olad won't start as root. I enabled the service and rebooted but service didn't start. I got the following error(using journalctl):

```
Jul 06 20:11:12 archlinux olad[465]: olad/OlaServer.cpp:186: No network interface found
Jul 06 20:11:13 archlinux olad[465]: *** WARNING *** The program 'olad' uses the Apple Bonjour compatibility layer of Avahi.
Jul 06 20:11:13 archlinux olad[465]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jul 06 20:11:13 archlinux olad[465]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
```

So I thought that olad has dependency for avahi. I searched and found out that systemd already have avahi-daemon.service  avahi-dnsconfd.service files installed. I added these as dependency to  olad unit file:

```
[Unit]
Description=OLA Daemon
Requires=avahi-daemon.service avahi-dnsconfd.service
After=avahi-daemon.service avahi-dnsconfd.service

[Service]
ExecStart=/usr/local/bin/olad --daemon --syslog
User=alp

[Install]
WantedBy=multi-user.target
```

So I enabled these 2 avahi services and rebooted but got the same error. I think this dependency can't be satisfied because olad starts as user service and avahi services start as root(I checked their unit files). So I added "User=alp" to the avahi service unit files but got the following error for avahi after reboot. olad service didn't give me any error at journalctl this time.

```
Jul 07 19:45:24 archlinux avahi-dnsconfd[422]: This program is intended to be run as root.
Jul 07 19:45:25 archlinux avahi-daemon[423]: This program is intended to be run as root.
```
I can't think of anything else to try. By the way I tried running olad service as root but it didn't work. I don't get any errors at journalctl but I know service fails(by running 'systemctl status olad.service').

I know most probably that this isn't an issue related to OLA and here may not be the appropriate place to ask but maybe someone had some experience with this to help me. Any help is appreciated.

**Comment by alphancioglu** [comment]
I figured it out. Avahi is not the problem. I forgot to add Type=forking to the unit file. It was pretty stupid of me to miss this but that avahi warning redirected my concentration. Below is the final unit file if someone needs it.

```
[Unit]
Description=OLA Daemon

[Service]
ExecStart=/usr/local/bin/olad --daemon --syslog
User=alp
Type=forking

[Install]
WantedBy=multi-user.target
```

**Comment by shenghaoyang** [comment]
Hmm... are you also running ``OLAd`` embedded in something? If you're running as your user, you might as well run the service under ``systemd`` in user mode, and enable linger in order to have the service run at startup - that's what I did in order to avoid having to write my own service file to the protected `/etc/systemd/system` unit file directory - not sure which is better, I just chose the one that was easier to maintain.

I was a little hesitant enabling the daemon functionality - I couldn't find where the PIDFile for ``olad`` is in ``man olad``, and in that case ``systemd`` has to guess the ``PID`` of the child process. (Maybe someone could implement ``sd_notify()`` in OLAd for proper notification of daemon startup?)

If you're having problems with ``avahi`` - and you're not using the ``dns-sd`` functionality of ``olad``, you can add ``--no-register-with-dns-sd`` to the ``olad`` command line.

On a side note: you don't have to add ``--syslog`` - ``systemd`` captures ``stderr`` and forwards them to the journal as well. 

Here's the unit file I have - I added in a bunch of sandboxing options just for kicks.
```
[Unit]
Description=ola daemon service
Requires=default.target
After=default.target

[Service]
WorkingDirectory=/home/alarm/.ola
BindPaths=/home/alarm/.ola

NoNewPrivileges=True
ProtectSystem=strict
ProtectHome=tmpfs
ProtectKernelTunables=True
ProtectControlGroups=True
LockPersonality=True
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX

RestrictNamespaces=True
MountFlags=private

SystemCallFilter=~@cpu-emulation
SystemCallFilter=~@clock
SystemCallFilter=~@debug
SystemCallFilter=~@keyring
SystemCallFilter=~@module
SystemCallFilter=~@mount
SystemCallFilter=~@obsolete
SystemCallFilter=~@privileged
SystemCallFilter=~@raw-io
SystemCallFilter=~@reboot
SystemCallFilter=~@setuid
SystemCallFilter=~@swap
SystemCallErrorNumber=EPERM
SystemCallArchitectures=native

Type=simple
ExecStart=/usr/bin/olad --no-register-with-dns-sd

MemoryHigh=5%
MemoryMax=10%

[Install]
WantedBy=default.target
```

**Comment by alphancioglu** [comment]
@shenghaoyang 
I won't be using olad in embedded and I will always setup the pc beforehand so I have access to root directories. Therefore I use the /etc/systemd/system directory and not use systemd in user mode because I want the service to be available to all users. I don't want to  deal with this setup again if a user is added or removed afterwards. I run the process as a user instead of root only because olad doesn't run as root. If it would run as root I would run it as root. 

I am running `olad --syslog --daemon` because that is the started process command when c++ api is invoked. I discovered it by `ps ax`. I am running olad before my program is executed because ola api doesn't list the connected usb devices at first program execution. It lists after first execution which I figured that olad wasn't running at first. I don't know what you are talking regarding daemon option and I am sticking with it because it is the default and it works. I am a beginner in linux so I don't mess with system functionality if I don't have to :smile: 

Avahi was a warning and I discovered that same warning appear in different open source projects so I don't care. 

Thanks for the suggestions.

**Comment by shenghaoyang** [comment]
>
> The other error will probably be partly due to trying to start olad before
> networking is up. I believe there's some magic way to do that in systemd.
> People keep asking about systemd and promising to add their example configs
> in a pull request, but no-one has done so yet. For info, the Debian install
> creates an olad user to run olad as.
>
Well, a template unit file is a bit of a problem, because we have to
specify the username and group to run as, and that isn't really known
because install scripts may create different user and group combinations
for running olad. I'm a little bit interested in the `DynamicUser`
functionality, though, but this requires that olad load its configuration
files from another directory rather than `~/.olad`, because I don't think
systemd emulates a persistent home directory for dynamically created
service users, but these services do get a persistent directory under
`/var/lib`.

But yes, one could place a dependency on the network for olad to start,
though I can't remember what exactly systemd defines as `network being up`.
For olad, it's just `lo` for RPC, right?

> @shenghaoyang <https://github.com/shenghaoyang> we don't currently write
> a PID file for the daemon, we get start-stop-daemon to do it on Debian:
>
> https://github.com/OpenLightingProject/ola/blob/master/debian/ola.olad.init#L40
>
> Pull requests welcome for that and sd_notify() functionality, we've
> already got lock file creation for serial ports, so the code is practically
> there:
>
> https://github.com/OpenLightingProject/ola/blob/0.10/common/io/Serial.cpp#L144
>
> Yeah, I might send in a request for that. I'm not that good with
autotools, though (chickened out to use Scons), so I'll need a little help
with defining the macro that switches in / out the call to `sd_notify()`
and links against `libsystemd` as needed. A PID file is moot in this case
since notifying services aren't really meant to fork and demonize
themselves - they let systemd take care of that for them. If you could
point me to the point where olad finishes initialization and is ready to
accept RPC, then adding `sd_notify()` is trivial. Even better, we could add
it to the deferred SIGHUP handler and notify on config reloads - that isn't
strictly necessary, but might help systemd order stuff around.

Shenghao

>
