### ISSUE TITLE
OLA not finding custom PIDs

### ISSUE THREAD

**Issue by ltd9938** [OpenLightingProject/ola#1470]
I just received a new firmware for our fixtures along with a .proto file for our custom PIDs. This article (https://opendmx.net/index.php/RDM_PID_Definitions) says to place the .proto file in the /usr/local/share/ola/pids/ directory.

The ola folder in the share directory didn't exist so I had to create it. I placed the file in the newly created pids directory and restarted ola. When testing the new pids OLA keeps saying it's an unknown PID.

I installed ola via git in my home directory if this helps.

**Comment by ltd9938** [comment]
Got it. 

My directory was /usr/local/share/ola/pids

**Comment by peternewman** [comment]
Hi @ltd9938 ,

Glad you got it sorted, although I'm a bit confused, as the directory you list, and the one the instructions mention are identical!

Are these PIDs private manufacturer ones for factory based config, or are they general purpose user ones? If the latter, can you open a pull request or an issue against https://github.com/OpenLightingProject/rdm-app with the file so we can get them added to the RDM site for general use:
http://rdm.openlighting.org/

You may also want to use the RDM model collector to add your fixtures to the website too:
https://wiki.openlighting.org/index.php/Using_the_RDM_Test_UI#RDM_Responder_Publisher

Finally, it seems it's not made it into our documentation yet, but you may like to know about the override functionality that's now in the PID definitions:
https://github.com/OpenLightingProject/ola/issues/732

So you can just use a overrides.proto file while testing the custom PID, rather than having to overwrite the entire set of PID definitions.
