### ISSUE TITLE
Android app UI Issue and issue with login with forgot password

### ISSUE THREAD

**Issue by Varun108** [OpenLightingProject/ola#1585]
Simulation steps: ->
1. UI Issue (Someone with very weak eyesight will face this issue):
a. Go to settings and increase the font size to the maximum.
b. Open the OLA app 
c. There is no scroll for any page and some words overlap other words

2. Login Issue:
a. Use login with phone number/Google/Facebook option to login.
b. Enter the phone number / click on gmail ID /click on  FB ID 
c. In case of phone number, OTP will be auto detected and the app will redirect to enter password page.
c. App will prompt to enter the password. Click on "Get a call".
d. Pick up the call and follow the instructions. At the end the lady on the call will say "you are now logged in" and the call will get disconnected.
e. You get back to app and nothing happens.
f. Also, the call on *some number* does not work. The number given on the app is an invalid number.

**Comment by peternewman** [comment]
Hi @Varun108 ,

We're entertainment lighting control software and don't have an official app, Android or otherwise, just some attempted compilation instructions:
https://wiki.openlighting.org/index.php/OLA_on_Android

I'm guessing you're actually looking for a taxi or chat app, in which case that's not us sorry.

I'm going to close this, but please feel free to reopen it if I've misunderstood things.
