### ISSUE TITLE
Problem with python version 3.10 test

### ISSUE THREAD

**Issue by mikacousin** [OpenLightingProject/ola#1755]
Hi,
I just found a bug with the python version check.
It does not work with python 3.10.

Currently, we have:
`if sys.version >= '3.2':`
which does not match with 3.10.

It looks like this is working:
`if sys.version_info >= (3, 2):`

Regards

**Comment by peternewman** [comment]
Hi @mikacousin ,

Thanks for reporting.

I was initially a bit confused, but its obviously because the broken version is doing a naïve string comparison and 1 < 2!

I assume you mean here (and elsewhere in that file):
https://github.com/OpenLightingProject/ola/blob/c9add79a8d1c83ab209146006dae87906803b64f/python/ola/PidStore.py#L661

And likewise (and elsewhere):
https://github.com/OpenLightingProject/ola/blob/c9add79a8d1c83ab209146006dae87906803b64f/python/ola/OlaClient.py#L955

We already do that in https://github.com/OpenLightingProject/ola/blob/c9add79a8d1c83ab209146006dae87906803b64f/include/ola/gen_callbacks.py#L25

So we should be good.

Was that all you needed to fix Python 3.10 compatibility? Would you mind opening a PR with those changes please?

Would you mind testing #1723 please while you're there, so we can get that merged in too, and then I think we'll hopefully be properly Python 3 compatible!

**Comment by mikacousin** [comment]
Hi @peternewman,

That's the only problem I found with python 3.10 for now :-)
PR is done, but I'll test #1723 in a few days if I found some time ...
Thanks a lot for all your work on ola !

**Comment by peternewman** [comment]
> That's the only problem I found with python 3.10 for now :-)

:crossed_fingers: Roughly what have you done of these via Python:
Send DMX
Receive DMX
Patch universes
List plugins
Send RDM

> PR is done, but I'll test #1723 in a few days if I found some time ...

Great thanks.

> Thanks a lot for all your work on ola !

No worries

**Comment by peternewman** [comment]
Fixed in #1757
