### ISSUE TITLE
SetDmxFailMode swaps losstime & holdtime in RDM Responder Test

### ISSUE THREAD

**Issue by jensgol** [OpenLightingProject/ola#1842]
Hello,
the test "Set DMX_FAIL_MODE without changing the settings" gets loss_time=2.0 and hold_time=0 from my responder, but the SET test scrambles both values in the SET protocol, so that my device fails.
Maybe this is an problem in the order of both fields, in E1.20 the losstime comes before the holdtime and not as written below: 
'scene_number': 0, 'hold_time': 0.0, 'loss_of_signal_delay': 2.0, 'level': 0
[0, 0.0, 2.0, 0]

so it should be 
'scene_number': 0, 'loss_of_signal_delay': 2.0, 'hold_time': 0.0, 'level': 0
[0, 2.0, 0.0, 0]

GET: uid: 4c53:530f002f, pid: DMX_FAIL_MODE (0x0141), sub device: 0, args: []
 Response: RDMResponse(type=ACK, command_class=GET), PID: 0x0141, TN: 35, PDL: 7, data: {'scene_number': 0, 'hold_time': 0.0, 'loss_of_signal_delay': 2.0, 'level': 0}

Category: DMX512 Setup
Result: Failed
Debug Output:
 SET: uid: 4c53:530f002f, pid: DMX_FAIL_MODE (0x0141), sub device: 0, args: [0, 0.0, 2.0, 0]
 Response: RDMResponse(type=NACK, reason="Data out of range"), PID: 0x0141, TN: 37
 Failed: expected one of:
  CC: Set, PID 0x0141, NACK RDMNack(value=4, desc="Write protect")
  CC: Set, PID 0x0141, ACK, fields [], values {}
  CC: Set, PID 0x0141, NACK RDMNack(value=5, desc="Unsupported command class")

**Comment by peternewman** [comment]
Another good spot @jensgol . This has also been broken since it went in as part of 5369e33 and 959450a .

I guess you found it as you support a different range of values for one compared to the other?

Internally we name the fields and that was all correct, but passing in the arguments to populate those fields in an array they were simply the wrong way round.

I've fixed it in #1842 (along with the other one) if you'd like to give it a test and check that's resolved your issues?

**Comment by peternewman** [comment]
Let us know if this doesn't fix it for you @jensgol .
