### ISSUE TITLE
ola_streaming_client not getting released?

### ISSUE THREAD

**Issue by kengruven** [OpenLightingProject/ola#1876]
I'm probably just missing something obvious, but I'm seeing changes in the `ola_streaming_client` source code which don't seem to exist in any releases.

- [the online manpage](https://docs.openlighting.org/ola/man/man1/ola_streaming_client.1.html), "Updated: July 2013" (sic?), has option "-s, --universe-from-stdin"
- [the source code for the manpage](https://github.com/OpenLightingProject/ola/blob/master/man/ola_streaming_client.1) shows option "-s", and the blame for that line shows it was last touched in 2020
- [the source code for the program](https://github.com/OpenLightingProject/ola/blob/master/examples/ola-streaming-client.cpp) shows this option, and the blame for that line shows it was last touched at the same time, in 2020

And yet:
- [the latest release of OLA](https://github.com/OpenLightingProject/ola/releases/tag/0.10.9) is 0.10.9, from earlier in 2023
- the source downloads for 0.10.9 (zip or tar.gz) don't include any "universe-from-stdin" option, in either the manpage or source code
- [browsing the 0.10.9 tag on GitHub](https://github.com/OpenLightingProject/ola/tree/refs/tags/0.10.9) doesn't show any "universe-from-stdin" option in either file

Why am I not seeing `--universe-from-stdin` in any release, even though it was added before 0.10.8?

**Comment by kengruven** [comment]
I looked at this again, and either I'm not understanding the OLA release process, or I'm not understanding git, or there are a lot of changes that have never been in a "release".

```
$ git cherry -v 0.10.9 master | wc -l
1270
```

Only about 10% of these are dated 2023, so 90% of these predate 0.10.9.  As a basic check, this list does include the changeset which originally added the "ola_streaming_client -s" feature (1e8328e12ae7024324872f5b6aeb1af929ba5ebd).

Looking at the list, I see several changes related to "ShowJockey".  That's a plugin in "plugins/usbdmx/ShowJockeyDMXU1.h" on master.  It was renamed from plain "ShowJockey.h" in 2017, and was originally added in 2016.  As far as I can tell, no tagged release of OLA ever included ShowJockey support.  Same with Nanoleaf, and SPIDMX, and AVLdiy, and DMXCreator.

Does OLA have tens of thousands of lines of code on 'master' that have never been released?

**Comment by peternewman** [comment]
Hi @kengruven ,

Our release process is detailed in one of our README files:
https://github.com/OpenLightingProject/ola/blob/5fa67e56dc92985ea1ad2a3ac9c84484a76db37d/README.developer#L49-L72

Admittedly we've not been getting major releases out as frequently as I'd like due to an ongoing flood of significant bugs and not enough people working on fixing them or testing stuff. If you'd like to volunteer your services we'd certainly appreciate the help:
https://github.com/OpenLightingProject/ola/blob/master/CONTRIBUTING

We're not really aiming for move fast and break things, given the majority of users won't need e.g. Nanoleaf support, they'll just want a stable system to keep pumping DMX in or out, @DaAwesomeP has been doing some great work to get nightly builds, which should be in soon which will help things for people that do need some of those as-yet unreleased features.

See also some discussion in #1792 previously.

Regarding:

>     * [the online manpage](https://docs.openlighting.org/ola/man/man1/ola_streaming_client.1.html), "Updated: July 2013" (sic?), has option "-s, --universe-from-stdin"

Our man pages and doxygen are auto-generated from the master branch whenever it changes, hence the difference there.  Regarding the update date, we've a `--gen-manpage` option for most of our binaries, which would insert the correct date, however it currently needs some hand-cranking as it doesn't know about the SEE ALSO and EXAMPLES sections. PRs very welcome to automate that process more, merging a manually written footer onto the auto-generated header from the command.

**Comment by DaAwesomeP** [comment]
@peternewman it might be possible to add a version drop down to the documentation. That's become a really great feature with sites like readthedocs. Some of these newer tools also parse Doxygen so we could look into that if Doxygen won't do it by itself.

Or at the very least maybe we should have an index page that link to subfolders to allow for choosing between a released version and master. We can do this in a way that doesn't break permalinks. We can also absolutely aim to eventually have the master documentation published on push if we want to. Building documentation is on my list, though I'd like to get the current pulls finished first.

**Comment by kengruven** [comment]
Oooh.  I apologize.  I didn't realize that all of the changes (some of them seeming rather significant) on 0.10.* were only considered bug fixes.  Also, there's some unreleased changesets from well before 0.10.0, though it's hard to tell if they're (still) relevant.

I guess the simple answer for me is: there hasn't been a "release" in 7 years.  So I tried building from git master, and `ola_streaming_client -s` works mostly as expected.  Anyway, I'm happy to help in general, but I don't really know C++ or autotools or protoc, so I think my utility is somewhat limited outside of manual testing.
