### ISSUE TITLE
DMXking ultraDMX Max USB detected as UART native DMX 	/dev/ttyACM0

### ISSUE THREAD

**Issue by DavidOpgh** [OpenLightingProject/ola#1972]
I believe it should be using the Serial USB plugin. 

Can someone explain how I can configure OLA to fix this?

**Comment by peternewman** [comment]
Have a look at our FAQ @DavidOpgh :
https://www.openlighting.org/ola/get-help/ola-faq/#What_is_the_difference_between_the_different_USB_plugins

I suspect you've got the FTDI USB DMX plugin enabled rather than the Serial USB/USB Pro.

I assume this device is supposed to use the Enttec USB Pro protocols, I found it rather hard to tell from their specs.

Actually the device path/chip used will have probably confused things, as mentioned here:
https://docs.openlighting.org/ola/conf/ola-usbserial.conf.html

Try adding a line like this to your ola-usbserial.conf:
`device_prefix = ttyACM`

If that doesn't work please can you share your olad -l 4 logs as explained here:
https://www.openlighting.org/ola/get-help/ola-faq/#How_do_I_get_olad_-l_4_logs

**Comment by gobo-ws** [comment]
QLC+ supports DMXKing ultraDMX MAX. https://github.com/mcallegari/qlcplus/blob/cb35bba00f46fe200a12c0ed2542cd40d3f1eda3/plugins/dmxusb/src/dmxinterface.h#L98 if that could be useful.

**Comment by DavidOpgh** [comment]
> 
> Try adding a line like this to your ola-usbserial.conf: `device_prefix = ttyACM`
> 

Yes, thank you.  Adding that line to ola-usbserial.conf did the trick! Working just fine now!
