### ISSUE TITLE
UX feed back

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/ola#635]
Here are my comments after playing with the new UI for a bit. 

- Can you set the page <title> to the instance name & IP address. Doing so helps differentiate different instances of OLA

- It wasn't immediately obvious how to get back to the original page once I was adding a new universe. Can you add a 'System' / 'Home' item to the menu. See http://picpaste.com/UI-mocks-3w9syD1d.png 

- From looking at UX like Gmail & github. They both use two different buttons. Blue / Red / Green buttons are used to draw the user's attention, e.g. "Compose" and "Submit new issue". Grey buttons are used for less frequently used features like "Remove label" and "Fork".

- Following that I'd change the "Shutdown" button on the first page to a grey one. Since I don't expect it to be used often.

- On that note, I'd add a colored "Add new universe" button to the front page. So a user arriving at the UI for the first time has a hint of what to do to get started. See http://picpaste.com/UI-mocks-3w9syD1d.png

- When the shutdown button is pressed. Add a note that OLA may not restart automatically. This is important since the user may not have ssh access and may have to power cycle the host if they shut down olad.

- On the plugins page, it's not immediately clear that the plugin names / rows are clickable. It may be worth adding an "Info icon" (I) to hint to the user.

- On the plugins page, can you add a 'reload' plugins button at the top. It should be grey not colored.

- I'd make the universe overview page what you get if you click directly on the 'Universes' link at the top of the page, and remove it from the drop down menu

- I'd also move 'Add Universe' to the top of the drop down. 

That's it for now. I'll go over the universe settings one next.

**Comment by daveol** [comment]
I think everything on this list addressed now, if you can check this that would be great.

**Comment by peternewman** [comment]
When I click home, it seems to reload the page twice.

The button colours look fine and shutdown has the new note.

The reload plugins button needs to also refresh the data displayed, or it won't see the changes (edit the enabled state of a plugin in it's config file while running to reproduce, the dot colours only change when you reload the page too).

Clicking on the Universes menu just gives the drop down rather than the overview. This may be functional incompatibilities between what @nomis52 wants and what Angular can do.

As another bit, can we maybe have the universe ID in brackets after the name Bob (Id: 1) rather than on a new line taking up vertical space.

Can we have tooltips please for accessibility (lamp on/off, ednabled/active etc).

**Comment by daveol** [comment]
> When I click home, it seems to reload the page twice.

fixed, I pointed to /new/ instead of /new/#/
>The reload plugins button needs to also refresh the data displayed, or it won't see the changes (edit the enabled state of a plugin in it's config file while running to reproduce, the dot colours only change when you reload the page too).

fixed it now reloads if you click too
>Clicking on the Universes menu just gives the drop down rather than the overview. This may be functional incompatibilities between what @nomis52 wants and what Angular can do.

From what I understood this is intentional because the drop-down only  appears if you click on the menu item and the universes overview is now accessible when you click on the universes heading above the table with universes. 
> As another bit, can we maybe have the universe ID in brackets after the name Bob (Id: 1) rather than on a new line taking up vertical space.

I will play around with this and decide what looks best
> Can we have tooltips please for accessibility (lamp on/off, enabled/active etc).

[bootstrap](http://getbootstrap.com/javascript/#tooltips) or [html](http://www.w3schools.com/tags/att_global_title.asp) ?

**Comment by peternewman** [comment]
Great. I assume we'll have a new PR soon?

Ah, I hadn't realised that was clickable. I don't know what @nomis52 thinks, but I think having an overview link to get to there would be good. If you want to go say Plugins to Universe Overview, it seems odd you have to go via home and an extra click.

I'd say HTML for best compatibility with screen reader type things. Plus we don't "need" them for normal operation, so they don't need to look too shiny.

**Comment by nomis52** [comment]
Besides the Universe pull down menu, which we discussed, I have a couple of other comments:

- To keep with the theme the 'Add Universe' button on the new universe page should be blue, not grey since it's a primary action.

- Initially disabling the 'Add Universe' button was also a bit confusing. I realize we need to get the user to select one or more ports before clicking add but if they don't know that it's not immediately clear what to do. I'd instead leave the button enabled and pop up a message if it's clicked and there are no ports selected.

- Can you provide a hint in the Universe name text input. Perhaps 'downstage-spots' or something.

**Comment by daveol** [comment]
@nomis52 and @peternewman can you both either update your old or make a new comment with the things that need to be fixed?

**Comment by nomis52** [comment]
All my comments have been addressed. 

I like the split input / output ports. I think that works well.

I'm wondering if we even need the universe drop down menu now, since you can get to a universe from either the front page or the universe summary page. Maybe leave it in for now until we get some more user feedback.

**Comment by peternewman** [comment]
One thing for starters, if the universe name field is left blank, it sets the name to the string undefined, rather than defaulting to "Universe n". Can you also make the text hint dimmer please.

**Comment by peternewman** [comment]
I need to have another proper look at the list, but it won't be until later tonight/tomorrow.
