### ISSUE TITLE
Minor fixes for the new UI

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/ola#679]
On the Faders page:

- Can you add a checkbox 'activate console' that is unchecked by default. The problem we have right now for both the old and new UI is that switching to the faders tab generates a universe of 0s, which will cause flickering if the universe is set to LTP merge mode. Forcing the user to take an explicit 'activate' action would avoid this.
- When I click the forward / back buttons in the console my browser highlights them. I think they are getting focus. See screenshot.
-  I think making the blue band more of a toolbar and making the buttons in grey would help stand out. 
- If we had such a toolbar, it would be nice to have a numeric input as well. e.g. Channel X and Y . 

On the Universe settings page:
 - If the only option is 'static', I think it should be grey text, rather than something that looks like a text input field
 - Right now there is no feedback if a port patch fails, for example, trying to patch an E1.33 port to universe 0 silently fails. The CLI suffers from the same problem. We should return an error message back in the RPC and display this in the UI.
![screen shot 2015-03-14 at 2 06 40 pm](https://cloud.githubusercontent.com/assets/4355332/6739677/9ba9f290-ce50-11e4-8708-fb6aabc24312.png)

**Comment by daveol** [comment]
> - Can you add a checkbox 'activate console' that is unchecked by default. The problem we have right now for both the old and new UI is that switching to the faders tab generates a universe of 0s, which will cause flickering if the universe is set to LTP merge mode. Forcing the user to take an explicit 'activate' action would avoid this.

Actually the new ui only sends data if you click one of the faders and it cuts of any zero's that are not needed so I'm not sure what you are talking about. if you are talking about the zero's you can see i generate those because I first fill the array to the limit of what the api gives me  and the rest are all zero's to make the faders not freak out and say NaN.

> - I think making the blue band more of a toolbar and making the buttons in grey would help stand out.

I will play around with this and look at what is best.

> - If we had such a toolbar, it would be nice to have a numeric input as well. e.g. Channel X and Y .

For the pages? It's not really clear what you mean.

**Comment by nomis52** [comment]
Ah ok, maybe this isn't a problem with the new console.

I've attached a mock up of what I was suggesting:

![screen shot 2015-03-22 at 10 27 48 am](https://cloud.githubusercontent.com/assets/4355332/6769790/25c83ec0-d07f-11e4-8849-67b5bed9e89d.png)

**Comment by daveol** [comment]
okay, I will comment on each of the points of the original list to get the status of the issue:

> - Can you add a checkbox 'activate console' that is unchecked by default. The problem we have right now for both the old and new UI is that switching to the faders tab generates a universe of 0s, which will cause flickering if the universe is set to LTP merge mode. Forcing the user to take an explicit 'activate' action would avoid this.

This actually is not a issue see the earlier comment [here](/OpenLightingProject/ola/issues/679#issuecomment-84003455). However if there is still weird behavior I will look in to it, currently I see no problem in the ui. 

> - When I click the forward / back buttons in the console my browser highlights them. I think they are getting focus. See screenshot.

This was fixed in pull request #685 and thus is not a issue anymore.

> - I think making the blue band more of a toolbar and making the buttons in grey would help stand out.
> - If we had such a toolbar, it would be nice to have a numeric input as well. e.g. Channel X and Y .

I don't know if this is a good idea because there is a supposed to be a separate keypad tab.
Thoughts? @peternewman @nomis52 

> - If the only option is 'static', I think it should be grey text, rather than something that looks like a text input field

I made the background grey in pull request #685. So this is fixed.

> - Right now there is no feedback if a port patch fails, for example, trying to patch an E1.33 port to universe 0 silently fails. The CLI suffers from the same problem. We should return an error message back in the RPC and display this in the UI. 

As I understand correctly there is currently no way of receiving these error messages, as soon as this is implemented server-side I will implement it client-side too.

**Comment by nomis52** [comment]
Is the output from the keypad tab  independent, or does it override the sliders ? I assumed it was the former but may be wrong.

I think it would be nice to combine the sliders and keypad onto a single tab.

**Comment by peternewman** [comment]
If we do put a basic keypad in the toolbar, we should use at/@ rather than to, so it's less ambiguous about whether we're selecting a range or setting a channel to a value. The old UI keypad is much more fully featured and would be a better bet anyway I'd say.

**Comment by daveol** [comment]
As I see it now there are three points sill open in this issue:
> - I think making the blue band more of a toolbar and making the buttons in grey would help stand out.
> - If we had such a toolbar, it would be nice to have a numeric input as well. e.g. Channel X and Y

Do we still want this? We have a fully operational keypad in the new ui now.
> - Right now there is no feedback if a port patch fails, for example, trying to patch an E1.33 port to universe 0 silently fails. The CLI suffers from the same problem. We should return an error message back in the RPC and display this in the UI. 

Is there a error code returned yet?

**Comment by daveol** [comment]
any updates on this?

**Comment by nomis52** [comment]
Nothing on the server side.

**Comment by daveol** [comment]
but we still want the toolbar... thing?

**Comment by nomis52** [comment]
I think we're ok now.

**Comment by daveol** [comment]
so this can be closed?
