### ISSUE TITLE
Allow for overriding PID definitions.

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/ola#732]
Use case:

A manufacturer has a custom PID that is normally GET only. However in the factory, they use the OLA tools to send SET commands as part of programming the unit. We don't want to publish the SET command on the rdm.openlighting.org website since it shouldn't be used outside the factory.

The proposal is to allow an *overrides.proto* file to override the PID definitions usually found in pids.proto & manufacturer_pids.proto . The manufacturer can then write their own overrides.proto with the SET command and use the tools as required. 

I think this is a pretty small change to the PidLoader.

**Comment by peternewman** [comment]
Looks like we'd just need to tweak GetPidList https://github.com/OpenLightingProject/ola/blob/master/common/rdm/PidStoreLoader.cpp#L192 to handle duplicates in some cases, or otherwise merge the results.

How do we handle collisions, I imagine it could be possible (but perhaps not advisable) to override an existing PID. E.g. device_label to have more fields that aren't listed, or similar with a manufacturer PID.

So do we only allow overriding of manufacturer PIDs? Do we allow a get/set request/response to be overridden and just load overrides.proto last if it exists?

**Comment by nomis52** [comment]
I'd just load overrides.proto last and replace anything in the store that appears in the override file. We should allow anything to be overridden, it's sort of a get-out-of-jail card.
