### ISSUE TITLE
Issues configuring ola to python on Os x system

### ISSUE THREAD

**Issue by jtl2018** [OpenLightingProject/ola#877]
So, I have been able to configure ola to the python API .  However, it's connecting to python 2.7 when I want it to connect to python 3.4.3, the python system I actually use.  When I check python in macports, I notice that python 3.4 is not an option.  For example, when I enter:
$port select python

Bash returns

none
python26-apple
python27 (active)
python27-apple

Any way of adding python 3.4 into MacPorts?  Sorry, I am not used to building open source projects, especially in Mac, as I normally use Python on Windows.  I've always been spoiled with pip for installing all the packages I need.

**Comment by nomis52** [comment]
protocol buffers  (which the ola Python module uses) does not yet support Python 3. @simark may have some pointers.

As for macports, I see Python34 listed at https://trac.macports.org/browser/trunk/dports/lang/python34/Portfile 

Have you tried running 

port install python34?

**Comment by jtl2018** [comment]
@nomis52 
Yeah it said I have "insufficient privileges".  Based on your statement that ola is not compatible with Python 3, I switched over to 2.7.1 for this program.  I ran:
cd (my ola folder)

export PATH=/opt/local/bin:$PATH:/usr/local/bin/ 
export PKG_CONFIG_PATH="/opt/local/lib/pkgconfig:$PKG_CONFIG_PATH"
export CPPFLAGS="-I/opt/local/include"
export LDFLAGS="-L/opt/local/lib"
export PYTHONPATH=/usr/local/lib/python2.7/site-packages/:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

./Configure --enable-python-libs
make
make check
sudo make install

After configuring, it said that the Python API was enabled, yet I do not see an ola folder in my site packages along with the fact that Python doesn't recognize:

import ola.ClientWrapper


Any Clue why this is happening?  Thanks for your help.

**Comment by simark** [comment]
At the end of configure, which Python interpreter is shown?

For example:

```
-------------------------------------------------------
OLA Version 0.9.7

Prefix: '/usr/local'
Compiler: 'g++ -g -O2 -pthread '
Linker: '/usr/bin/ld -m elf_x86_64  -ldns_sd  -ldl '
Python: /usr/bin/python     <------ THIS

Python API: yes
Java API: no
Enable HTTP Server: no
RDM Responder Tests: no
Ja Rule: no
Enabled Plugins: artnet dummy e131 espnet gpio karate kinet milinst opendmx pathport renard sandnet shownet spi stageprofi openpixelcontrol uartdmx usbpro

Now type 'make [<target>]'
  where the optional <target> is:
    all          - build everything
    check        - run the tests
    doxygen-doc  - generate the html documentation
-------------------------------------------------------
```

Also, at the end of the "make install" step, try to decipher where the python files got installed. For example:
```
...
 /usr/bin/install -c -m 644 python/ola/rpc/SimpleRpcController.py python/ola/rpc/StreamRpcChannel.py python/ola/rpc/__init__.py '/tmp/ola-install/lib/python2.7/site-packages/ola/rpc'
```

**Comment by jtl2018** [comment]
@simark my final line is:

 /usr/bin/install -c -m 644 python/ola/rpc/SimpleRpcController.py python/ola/rpc/StreamRpcChannel.py python/ola/rpc/__init__.py '/usr/local/lib/python2.7/site-packages/ola/rpc'

**Comment by simark** [comment]
Using the appropriate Python (/usr/local/bin/python), are you able to
"import ola"?

**Comment by jtl2018** [comment]
I tried to open up the path you suggested, but terminal says
The file /usr/local/bin/python does not exist.

I then tried to open IDLE which lies in downloads, and it could not import ola.  Where should my PATH variable be targeting?

**Comment by simark** [comment]
> I tried to open up the path you suggested, but terminal says
> The file /usr/local/bin/python does not exist.

Oh well, it could be /usr/local/bin/python2.7 as well. We need to know which Python executable you are using. Could you give the output of this?
```
import sys
print(sys.version)
print('-----')
print(sys.executable)
print('-----')
print(sys.path)
```

**Comment by jtl2018** [comment]
sorry for the late reply, this is the output:

>>> 
2.7.10 (default, May 25 2015, 13:06:17) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
-----
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
-----
['/Users/tlazar/Documents', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages']
>>>

**Comment by simark** [comment]
Ok, so the Python you are using is `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python`. For this Python installation to automatically find packages, they should be installed in `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages`. However, OLA installs Python files at a location computed from the prefix (/usr/local/lib/python2.7/site-packages in your case). That makes it awkward, because it assumes that you are using the Python interpreter located at `$prefix/bin/python`, which is rarely the case when prefix is /usr/local. I opened #772 some time ago to make the Python module install through a setup.py. This makes it so that the install location is derived from the current Python interpreter. In your case, the files would end up in `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages`.

Still, I am surprised that it didn't work when you ran Python 2.7 with `/usr/local/lib/python2.7/site-packages` in your `PYTHONPATH`.

**Comment by jtl2018** [comment]
So is there a functional setup.py at the moment or is there another way to set up ola that would be more optimal?

**Comment by simark** [comment]
Oh sorry, no there isn't. I opened a PR, but I didn't really follow-up on it, since there was not much excitement from anybody else :). You seem to be a real-life example of why it would be useful though, so maybe I should revisit it.

As a simple fix to make it work (tm), you could try to simply copy the files in your Python install. I just tried to do it with a virtualenv and it worked. Something along the lines of:

```
$ cp -a python/ola /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
```
when in the base of OLA's source directory. Then you wouldn't need to set PYTHONPATH at all.

**Comment by jtl2018** [comment]
Awesome, it works, and I got my script to work with OLA as well.  Thanks for being so helpful/understanding!

**Comment by simark** [comment]
Thanks for your patience as well. This shows that there is room for improvement!

**Comment by simark** [comment]
@peternewman, I believe you can close the issue.
