### ISSUE TITLE
Universe ID to Artnet net:sub:port is incorrectly mapped 

### ISSUE THREAD

**Issue by swgrainger** [OpenLightingProject/ola#996]
Version: 0.9.5 (Binary Image)
Platform: Raspberry PI 2 B

When creating Universe 15 through the GUI, the artnet node address is set to 0:0:0 instead of 0:0:15. In addition, when creating Universe 21, the artnet node address is incorrectly set to 0:0:6 instead of 0:1:6

attached screen dumps show the universe config via the GUI and how the ports are seen by Jands Vista
<img width="1277" alt="screen shot 2015-12-28 at 23 05 28" src="https://cloud.githubusercontent.com/assets/16469221/12027340/dab90a42-adbc-11e5-8693-90391e52a433.png">
<img width="1274" alt="screen shot 2015-12-28 at 23 18 09" src="https://cloud.githubusercontent.com/assets/16469221/12027346/e2d5e948-adbc-11e5-8f6e-4bb77e8f17f4.png">
<img width="1125" alt="screen shot 2015-12-28 at 23 44 34" src="https://cloud.githubusercontent.com/assets/16469221/12027356/0b734f94-adbd-11e5-83de-c6eed68f8ca9.png">
<img width="1125" alt="screen shot 2015-12-28 at 23 44 53" src="https://cloud.githubusercontent.com/assets/16469221/12027357/0f63142c-adbd-11e5-9e2c-7cab2c2a5015.png">

**Comment by peternewman** [comment]
This should be partly fixed in 0.9.8 already @swgrainger , via https://github.com/OpenLightingProject/ola/issues/856. Currently universe numbers all have to be within the same net and subnet (so for a universe over 16, you'll need to edit the net and subnet in ola-artnet.conf. @nomis52 will know more of the detail behind it, if this is an OLA or ArtNet limitation. I think this also raises a new bug, using universes 5 and 21 for example, it' possible to transmit or receive on ArtNet universe 5 from two OLA universes simultaneously, I think patching the second one should fail normally.

**Comment by nomis52** [comment]
Yup, this universe 15 issue is already fixed.

The rest is a artifact of how the ArtNet protocol works.The dual patching is a working-as-intended.
